version: "3.3"

networks:
  kademlia_network:
    ipam: 
      config:
        - subnet: 172.16.238.0/24

services:
  kadfs-boostrap:
    image: kademlia:latest
    command: "--listen 0.0.0.0:4000 --origin"
    networks:
      - kademlia_network
  kadfs-nodes:
    image: kademlia:latest
    command: "--listen 0.0.0.0:4000 --bootstrap-id=0000000000000000000000000000000000000000 --bootstrap-ip=bootstrap:4000"
    links:
      - "kadfs-bootstrap:bootstrap"
    deploy:
      replicas: 99
      restart_policy:
        condition: on-failure

