version: "3.3"

networks:
  kademlia_network:

services:
  consul-server:
    image: consul-server
    command: -bootstrap-expect=1 -data-dir=/tmp/
    networks:
      kademlia_network:
        aliases:
          - consulserver
    deploy:
      endpoint_mode: dnsrr

  kadfs-nodes:
    image: kademlia:latest
    command: "--listen=0.0.0.0:4000 --s3listen=0.0.0.0:8080 --consul=true"
    links:
      - "kadfs-bootstrap:bootstrap"
    depends_on:
      - kadfs-bootstrap
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    networks:
      - kademlia_network

