version: "3.3"

networks:
  kademlia_network: {}

services:
  consul-server:
    image: consul-server
    command: -ui -bootstrap-expect=1 -data-dir=/tmp/ -bind=0.0.0.0 -client=0.0.0.0 -enable-script-checks
    ports:
      - published: 8500
        target: 8500
        mode: host
    networks:
      kademlia_network:
        aliases:
          - consulserver
    deploy:
      endpoint_mode: dnsrr

  kadfs-nodes:
    image: kademlia:latest
    command: "--listen=0.0.0.0:4000 --s3listen=0.0.0.0:8080 --consul=true"
    deploy:
      replicas: 50
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    networks:
      - kademlia_network

