version: "3.3"

networks:
  kademlia_network:

services:
  kadfs-bootstrap:
    image: kademlia:latest
    command: "--listen=0.0.0.0:4000 --origin=true"
    networks:
      kademlia_network:
        aliases:
          - kadfsbootstrap
    deploy:
      endpoint_mode: dnsrr
  kadfs-nodes:
    image: kademlia:latest
    command: "--listen=0.0.0.0:4000 --bootstrap-id=0000000000000000000000000000000000000000 --bootstrap-ip=kadfsbootstrap:4000"
    links:
      - "kadfs-bootstrap:bootstrap"
    depends_on:
      - kadfs-bootstrap
    deploy:
      replicas: 99
      restart_policy:
        condition: on-failure
      endpoint_mode: dnsrr
    networks:
      - kademlia_network

