// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Messages.proto

package Messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NetworkMessage struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Request              bool     `protobuf:"varint,2,opt,name=request,proto3" json:"request,omitempty"`
	Context              int32    `protobuf:"varint,3,opt,name=context,proto3" json:"context,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkMessage) Reset()         { *m = NetworkMessage{} }
func (m *NetworkMessage) String() string { return proto.CompactTextString(m) }
func (*NetworkMessage) ProtoMessage()    {}
func (*NetworkMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb86ddf19e16901, []int{0}
}
func (m *NetworkMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkMessage.Unmarshal(m, b)
}
func (m *NetworkMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkMessage.Marshal(b, m, deterministic)
}
func (dst *NetworkMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkMessage.Merge(dst, src)
}
func (m *NetworkMessage) XXX_Size() int {
	return xxx_messageInfo_NetworkMessage.Size(m)
}
func (m *NetworkMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkMessage proto.InternalMessageInfo

func (m *NetworkMessage) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *NetworkMessage) GetRequest() bool {
	if m != nil {
		return m.Request
	}
	return false
}

func (m *NetworkMessage) GetContext() int32 {
	if m != nil {
		return m.Context
	}
	return 0
}

func (m *NetworkMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Dabes struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dabes) Reset()         { *m = Dabes{} }
func (m *Dabes) String() string { return proto.CompactTextString(m) }
func (*Dabes) ProtoMessage()    {}
func (*Dabes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9eb86ddf19e16901, []int{1}
}
func (m *Dabes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dabes.Unmarshal(m, b)
}
func (m *Dabes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dabes.Marshal(b, m, deterministic)
}
func (dst *Dabes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dabes.Merge(dst, src)
}
func (m *Dabes) XXX_Size() int {
	return xxx_messageInfo_Dabes.Size(m)
}
func (m *Dabes) XXX_DiscardUnknown() {
	xxx_messageInfo_Dabes.DiscardUnknown(m)
}

var xxx_messageInfo_Dabes proto.InternalMessageInfo

func (m *Dabes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*NetworkMessage)(nil), "Messages.NetworkMessage")
	proto.RegisterType((*Dabes)(nil), "Messages.dabes")
}

func init() { proto.RegisterFile("Messages.proto", fileDescriptor_9eb86ddf19e16901) }

var fileDescriptor_9eb86ddf19e16901 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf3, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x8a,
	0xb8, 0xf8, 0xfc, 0x52, 0x4b, 0xca, 0xf3, 0x8b, 0xb2, 0xa1, 0x42, 0x42, 0x42, 0x5c, 0x2c, 0x25,
	0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x60, 0xb6, 0x90, 0x04, 0x17, 0x7b,
	0x51, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x8c, 0x0b,
	0x92, 0x49, 0xce, 0xcf, 0x2b, 0x49, 0xad, 0x28, 0x91, 0x60, 0x06, 0x6b, 0x80, 0x71, 0x41, 0x32,
	0x05, 0x89, 0x95, 0x39, 0xf9, 0x89, 0x29, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x30, 0xae,
	0x92, 0x22, 0x17, 0x6b, 0x4a, 0x62, 0x52, 0x6a, 0x31, 0x48, 0x49, 0x2e, 0xc4, 0x56, 0xb0, 0x6d,
	0x9c, 0x41, 0x30, 0x6e, 0x12, 0x1b, 0xd8, 0x9d, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86,
	0x7c, 0xfe, 0x67, 0xb9, 0x00, 0x00, 0x00,
}
