// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPC struct {
	MessageId            int32    `protobuf:"varint,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	SenderId             int32    `protobuf:"varint,2,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	ReceiverId           int32    `protobuf:"varint,3,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
	RemoteProcedure      string   `protobuf:"bytes,4,opt,name=RemoteProcedure,proto3" json:"RemoteProcedure,omitempty"`
	Length               int32    `protobuf:"varint,5,opt,name=Length,proto3" json:"Length,omitempty"`
	Request              bool     `protobuf:"varint,6,opt,name=Request,proto3" json:"Request,omitempty"`
	SenderIp             string   `protobuf:"bytes,7,opt,name=SenderIp,proto3" json:"SenderIp,omitempty"`
	SenderPort           string   `protobuf:"bytes,8,opt,name=SenderPort,proto3" json:"SenderPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPC) Reset()         { *m = RPC{} }
func (m *RPC) String() string { return proto.CompactTextString(m) }
func (*RPC) ProtoMessage()    {}
func (*RPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *RPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC.Unmarshal(m, b)
}
func (m *RPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC.Marshal(b, m, deterministic)
}
func (dst *RPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC.Merge(dst, src)
}
func (m *RPC) XXX_Size() int {
	return xxx_messageInfo_RPC.Size(m)
}
func (m *RPC) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC.DiscardUnknown(m)
}

var xxx_messageInfo_RPC proto.InternalMessageInfo

func (m *RPC) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *RPC) GetSenderId() int32 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *RPC) GetReceiverId() int32 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *RPC) GetRemoteProcedure() string {
	if m != nil {
		return m.RemoteProcedure
	}
	return ""
}

func (m *RPC) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *RPC) GetRequest() bool {
	if m != nil {
		return m.Request
	}
	return false
}

func (m *RPC) GetSenderIp() string {
	if m != nil {
		return m.SenderIp
	}
	return ""
}

func (m *RPC) GetSenderPort() string {
	if m != nil {
		return m.SenderPort
	}
	return ""
}

type FindDataMessage struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindDataMessage) Reset()         { *m = FindDataMessage{} }
func (m *FindDataMessage) String() string { return proto.CompactTextString(m) }
func (*FindDataMessage) ProtoMessage()    {}
func (*FindDataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *FindDataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDataMessage.Unmarshal(m, b)
}
func (m *FindDataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDataMessage.Marshal(b, m, deterministic)
}
func (dst *FindDataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDataMessage.Merge(dst, src)
}
func (m *FindDataMessage) XXX_Size() int {
	return xxx_messageInfo_FindDataMessage.Size(m)
}
func (m *FindDataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FindDataMessage proto.InternalMessageInfo

func (m *FindDataMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type SendDataMessage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataMessage) Reset()         { *m = SendDataMessage{} }
func (m *SendDataMessage) String() string { return proto.CompactTextString(m) }
func (*SendDataMessage) ProtoMessage()    {}
func (*SendDataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}
func (m *SendDataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataMessage.Unmarshal(m, b)
}
func (m *SendDataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataMessage.Marshal(b, m, deterministic)
}
func (dst *SendDataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataMessage.Merge(dst, src)
}
func (m *SendDataMessage) XXX_Size() int {
	return xxx_messageInfo_SendDataMessage.Size(m)
}
func (m *SendDataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataMessage proto.InternalMessageInfo

func (m *SendDataMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RPC)(nil), "messages.RPC")
	proto.RegisterType((*FindDataMessage)(nil), "messages.FindDataMessage")
	proto.RegisterType((*SendDataMessage)(nil), "messages.SendDataMessage")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x59, 0xdb, 0xa6, 0xc9, 0xa0, 0x14, 0xe6, 0x20, 0x83, 0x88, 0x84, 0x82, 0xb0, 0x27,
	0x2f, 0xfe, 0x04, 0x45, 0x28, 0x28, 0x84, 0xf1, 0x17, 0xac, 0xdd, 0xa1, 0xe9, 0xa1, 0xd9, 0xba,
	0xbb, 0xf5, 0xaf, 0x7b, 0x95, 0x4c, 0x63, 0x1b, 0x7a, 0x7b, 0xef, 0x7b, 0x6f, 0x87, 0x99, 0x85,
	0x9b, 0x9d, 0xa4, 0xe4, 0x36, 0xf2, 0xb4, 0x8f, 0x21, 0x07, 0x2c, 0x07, 0x9b, 0x96, 0xbf, 0x06,
	0x26, 0xdc, 0xbc, 0xe0, 0x3d, 0x54, 0x1f, 0x47, 0xb6, 0xf2, 0x64, 0x6a, 0x63, 0x67, 0x7c, 0x06,
	0x78, 0x07, 0xe5, 0xa7, 0x74, 0x5e, 0xe2, 0xca, 0xd3, 0x95, 0x86, 0x27, 0x8f, 0x0f, 0x00, 0x2c,
	0x6b, 0xd9, 0xfe, 0x68, 0x3a, 0xd1, 0x74, 0x44, 0xd0, 0xc2, 0x82, 0x65, 0x17, 0xb2, 0x34, 0x31,
	0xac, 0xc5, 0x1f, 0xa2, 0xd0, 0xb4, 0x36, 0xb6, 0xe2, 0x4b, 0x8c, 0xb7, 0x50, 0xbc, 0x4b, 0xb7,
	0xc9, 0x2d, 0xcd, 0x74, 0xca, 0xe0, 0x90, 0x60, 0xce, 0xf2, 0x7d, 0x90, 0x94, 0xa9, 0xa8, 0x8d,
	0x2d, 0xf9, 0xdf, 0x8e, 0xf6, 0xda, 0xd3, 0x5c, 0x87, 0x9e, 0x7c, 0xbf, 0xd7, 0x51, 0x37, 0x21,
	0x66, 0x2a, 0x35, 0x1d, 0x91, 0xe5, 0x23, 0x2c, 0xde, 0xb6, 0x9d, 0x7f, 0x75, 0xd9, 0x0d, 0x87,
	0x22, 0xc2, 0xb4, 0x75, 0xa9, 0xd5, 0xfb, 0x2b, 0x56, 0xdd, 0xd7, 0xfa, 0x47, 0x17, 0x35, 0xef,
	0xb2, 0xd3, 0xda, 0x35, 0xab, 0xfe, 0x2a, 0xf4, 0x63, 0x9f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xca, 0xa7, 0x03, 0x57, 0x69, 0x01, 0x00, 0x00,
}
