// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RPC struct {
	MessageId            int32    `protobuf:"varint,1,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	SenderId             string   `protobuf:"bytes,2,opt,name=SenderId,proto3" json:"SenderId,omitempty"`
	ReceiverId           string   `protobuf:"bytes,3,opt,name=ReceiverId,proto3" json:"ReceiverId,omitempty"`
	RemoteProcedure      string   `protobuf:"bytes,4,opt,name=RemoteProcedure,proto3" json:"RemoteProcedure,omitempty"`
	Length               int32    `protobuf:"varint,5,opt,name=Length,proto3" json:"Length,omitempty"`
	Request              bool     `protobuf:"varint,6,opt,name=Request,proto3" json:"Request,omitempty"`
	SenderAddress        string   `protobuf:"bytes,7,opt,name=SenderAddress,proto3" json:"SenderAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPC) Reset()         { *m = RPC{} }
func (m *RPC) String() string { return proto.CompactTextString(m) }
func (*RPC) ProtoMessage()    {}
func (*RPC) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *RPC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPC.Unmarshal(m, b)
}
func (m *RPC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPC.Marshal(b, m, deterministic)
}
func (dst *RPC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPC.Merge(dst, src)
}
func (m *RPC) XXX_Size() int {
	return xxx_messageInfo_RPC.Size(m)
}
func (m *RPC) XXX_DiscardUnknown() {
	xxx_messageInfo_RPC.DiscardUnknown(m)
}

var xxx_messageInfo_RPC proto.InternalMessageInfo

func (m *RPC) GetMessageId() int32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *RPC) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *RPC) GetReceiverId() string {
	if m != nil {
		return m.ReceiverId
	}
	return ""
}

func (m *RPC) GetRemoteProcedure() string {
	if m != nil {
		return m.RemoteProcedure
	}
	return ""
}

func (m *RPC) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *RPC) GetRequest() bool {
	if m != nil {
		return m.Request
	}
	return false
}

func (m *RPC) GetSenderAddress() string {
	if m != nil {
		return m.SenderAddress
	}
	return ""
}

type FindDataMessage struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindDataMessage) Reset()         { *m = FindDataMessage{} }
func (m *FindDataMessage) String() string { return proto.CompactTextString(m) }
func (*FindDataMessage) ProtoMessage()    {}
func (*FindDataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *FindDataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindDataMessage.Unmarshal(m, b)
}
func (m *FindDataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindDataMessage.Marshal(b, m, deterministic)
}
func (dst *FindDataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindDataMessage.Merge(dst, src)
}
func (m *FindDataMessage) XXX_Size() int {
	return xxx_messageInfo_FindDataMessage.Size(m)
}
func (m *FindDataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FindDataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FindDataMessage proto.InternalMessageInfo

func (m *FindDataMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type SendDataMessage struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataMessage) Reset()         { *m = SendDataMessage{} }
func (m *SendDataMessage) String() string { return proto.CompactTextString(m) }
func (*SendDataMessage) ProtoMessage()    {}
func (*SendDataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}
func (m *SendDataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataMessage.Unmarshal(m, b)
}
func (m *SendDataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataMessage.Marshal(b, m, deterministic)
}
func (dst *SendDataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataMessage.Merge(dst, src)
}
func (m *SendDataMessage) XXX_Size() int {
	return xxx_messageInfo_SendDataMessage.Size(m)
}
func (m *SendDataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataMessage proto.InternalMessageInfo

func (m *SendDataMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendContactListMessage struct {
	Contact              []*Contact `protobuf:"bytes,1,rep,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendContactListMessage) Reset()         { *m = SendContactListMessage{} }
func (m *SendContactListMessage) String() string { return proto.CompactTextString(m) }
func (*SendContactListMessage) ProtoMessage()    {}
func (*SendContactListMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}
func (m *SendContactListMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendContactListMessage.Unmarshal(m, b)
}
func (m *SendContactListMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendContactListMessage.Marshal(b, m, deterministic)
}
func (dst *SendContactListMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendContactListMessage.Merge(dst, src)
}
func (m *SendContactListMessage) XXX_Size() int {
	return xxx_messageInfo_SendContactListMessage.Size(m)
}
func (m *SendContactListMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendContactListMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendContactListMessage proto.InternalMessageInfo

func (m *SendContactListMessage) GetContact() []*Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type Contact struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}
func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (dst *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(dst, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Contact) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*RPC)(nil), "message.RPC")
	proto.RegisterType((*FindDataMessage)(nil), "message.FindDataMessage")
	proto.RegisterType((*SendDataMessage)(nil), "message.SendDataMessage")
	proto.RegisterType((*SendContactListMessage)(nil), "message.SendContactListMessage")
	proto.RegisterType((*Contact)(nil), "message.Contact")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x49, 0xbb, 0xb5, 0xeb, 0xd1, 0x39, 0x39, 0x17, 0x23, 0x88, 0x48, 0x29, 0x0a, 0xc5,
	0x8b, 0x5d, 0xb8, 0x27, 0x90, 0x15, 0xa1, 0x30, 0x61, 0xc4, 0x27, 0x88, 0xcd, 0x61, 0xed, 0xc5,
	0x5a, 0x6d, 0x32, 0xdf, 0xd7, 0x37, 0x91, 0xa6, 0x89, 0xba, 0xdd, 0xe5, 0xff, 0xf2, 0xb5, 0x9c,
	0xff, 0x04, 0xe6, 0x07, 0xd2, 0x5a, 0xee, 0x69, 0xf5, 0xd1, 0x77, 0xa6, 0xc3, 0xd8, 0xc5, 0xec,
	0x9b, 0x41, 0x28, 0x76, 0x1b, 0xbc, 0x85, 0xe4, 0x75, 0x44, 0xa5, 0xe2, 0x2c, 0x65, 0xf9, 0x54,
	0xfc, 0x01, 0xbc, 0x81, 0xd9, 0x1b, 0xb5, 0x8a, 0xfa, 0x52, 0xf1, 0x20, 0x65, 0x79, 0x22, 0x7e,
	0x33, 0xde, 0x01, 0x08, 0xaa, 0xa8, 0xf9, 0xb2, 0xb7, 0xa1, 0xbd, 0xfd, 0x47, 0x30, 0x87, 0x85,
	0xa0, 0x43, 0x67, 0x68, 0xd7, 0x77, 0x15, 0xa9, 0x63, 0x4f, 0x7c, 0x62, 0xa5, 0x73, 0x8c, 0x4b,
	0x88, 0xb6, 0xd4, 0xee, 0x4d, 0xcd, 0xa7, 0x76, 0x00, 0x97, 0x90, 0x43, 0x2c, 0xe8, 0xf3, 0x48,
	0xda, 0xf0, 0x28, 0x65, 0xf9, 0x4c, 0xf8, 0x88, 0xf7, 0x30, 0x1f, 0xe7, 0x78, 0x56, 0xaa, 0x27,
	0xad, 0x79, 0x6c, 0xff, 0x7c, 0x0a, 0xb3, 0x07, 0x58, 0xbc, 0x34, 0xad, 0x2a, 0xa4, 0x91, 0xae,
	0x12, 0x22, 0x4c, 0x6a, 0xa9, 0x6b, 0xdb, 0x34, 0x11, 0xf6, 0x3c, 0x68, 0xc3, 0x77, 0x67, 0x9a,
	0x92, 0x46, 0x5a, 0xed, 0x52, 0xd8, 0x73, 0x56, 0xc0, 0x72, 0xd0, 0x36, 0x5d, 0x6b, 0x64, 0x65,
	0xb6, 0x8d, 0x36, 0xde, 0x7e, 0x84, 0xb8, 0x1a, 0x29, 0x67, 0x69, 0x98, 0x5f, 0x3c, 0x5d, 0xaf,
	0xfc, 0xd6, 0x9d, 0x2d, 0xbc, 0x90, 0xad, 0x21, 0x76, 0x0c, 0xaf, 0x20, 0x28, 0x0b, 0x37, 0x49,
	0x50, 0x16, 0x43, 0x5d, 0x5f, 0x67, 0xdc, 0xb5, 0x8f, 0xef, 0x91, 0x7d, 0xbc, 0xf5, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x59, 0x0c, 0x03, 0x16, 0xcd, 0x01, 0x00, 0x00,
}
